
title: 'Blog & Notes'
description: 'Welcome to My Blog site'
themeConfig:
  repo: 'https://github.com/zhangwt-cn'
  repoLabel: 'GitHub'
  nav:
    - text: 'Home'
      link: '/' 
  
  sidebar: 'auto'
  lastUpdated: 'Last Updated'