name: Sync Issues to Blog

on:
  issues:
    types: [opened, edited, deleted, labeled, unlabeled]
  workflow_dispatch:
    inputs:
      sync_all:
        description: 'Sync all issues'
        required: false
        type: boolean
      issue_number:
        description: 'Issue number to sync'
        required: false
        type: number
      action:
        description: 'Action to perform (create/update/delete)'
        required: false
        type: choice
        options:
          - create
          - update
          - delete

jobs:
  sync_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub

      - name: Sync all issues
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.sync_all == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.BLOG_TOKEN }}
        run: python sync_issues.py --all

      - name: Sync single issue (workflow dispatch)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.issue_number != '' && github.event.inputs.action != ''
        env:
          GITHUB_TOKEN: ${{ secrets.BLOG_TOKEN }}
        run: python sync_issues.py --issue ${{ github.event.inputs.issue_number }} --action ${{ github.event.inputs.action }}

      - name: Sync issue (issue event)
        if: github.event_name == 'issues'
        env:
          GITHUB_TOKEN: ${{ secrets.BLOG_TOKEN }}
        run: |
          if [[ "${{ github.event.action }}" == "deleted" ]]; then
            python sync_issues.py --issue ${{ github.event.issue.number }} --action delete
          else
            python sync_issues.py --issue ${{ github.event.issue.number }} --action update
          fi