# This is a basic workflow to help you get started with Actions

name: sync issues blog

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: sync blog
        uses: zhangwt-cn/blog-archive@main
        with:
          api-github-token: ${{ secrets.API_GITHUB_TOKEN }}
          repo: ${{ secrets.REPO }}
          owner: ${{ secrets.OWNER }}
          git-user-name: zhangwt
          git-user-email: im.zhangwt@gmail.com
      
